name: forecast_service
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  # Python
  - python=3.11
  
  # Core dependencies
  - fastapi=0.104.*
  - uvicorn=0.24.*
  - pydantic=2.5.*
  - pydantic-settings=2.1.*
  
  # Database
  - motor=3.3.*
  - pymongo=4.6.*
  
  # ML/Forecasting
  - prophet=1.1.*
  - pytorch=2.1.*
  - pytorch-lightning=2.1.*
  - pytorch-forecasting=1.0.*
  - scikit-learn=1.3.*
  - pandas=2.1.*
  - numpy=1.24.*
  
  # MLflow
  - mlflow=2.8.*
  - joblib=1.3.*
  
  # Utilities
  - python-dotenv=1.0.*
  - python-multipart=0.0.*
  - httpx=0.25.*
  
  # Testing
  - pytest=7.4.*
  - pytest-asyncio=0.21.*
  - testcontainers=3.7.*
  
  # Development
  - jupyter=1.0.*
  - matplotlib=3.8.*
  - seaborn=0.13.*
  
  # Optional GPU support
  - cudatoolkit=11.8  # Remove if CPU-only
  
  # Pip dependencies
  - pip
  - pip:
    - optuna==3.4.*  # For hyperparameter optimization
    - wandb==0.16.*  # Alternative to MLflow