# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sales_event.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11sales_event.proto\x12\x05sales"[\n\nSalesEvent\x12\x0b\n\x03sku\x18\x01 \x01(\t\x12\x0b\n\x03qty\x18\x02 \x01(\x05\x12\r\n\x05price\x18\x03 \x01(\x01\x12\n\n\x02ts\x18\x04 \x01(\t\x12\x10\n\x08\x65vent_id\x18\x05 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x06 \x01(\x0c\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sales_event_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_SALESEVENT']._serialized_start=28
  _globals['_SALESEVENT']._serialized_end=119
# @@protoc_insertion_point(module_scope)


class SalesEvent(_message.Message):
    __slots__ = ["sku", "qty", "price", "ts", "event_id"]
    SKU_FIELD_NUMBER: _ClassVar[int]
    QTY_FIELD_NUMBER: _ClassVar[int]
    PRICE_FIELD_NUMBER: _ClassVar[int]
    TS_FIELD_NUMBER: _ClassVar[int]
    EVENT_ID_FIELD_NUMBER: _ClassVar[int]
    sku: str
    qty: int
    price: float
    ts: str
    event_id: str
    def __init__(self, sku: _Optional[str] = ..., qty: _Optional[int] = ..., price: _Optional[float] = ..., ts: _Optional[str] = ..., event_id: _Optional[str] = ...) -> None: ...